channels:
  - conda-forge
dependencies:
  - aiohttp>=3.9.3
  - asciitree
  - botocore<1.36
  - cloudpickle
  - configobj
  - cryptography>=44.0.1
  - dask
  - dask-expr
  - dask-image
  - donfig=0.8.1.post1
  - defusedxml
  - dpath
  - fasteners
  - fsspec
  - gdal
  - git
  - h5netcdf
  - h5py
  - hdf5plugin
  - jinja2>=3.1.6
  - locket
  - netcdf4
  - netifaces
  - numcodecs
  - numpy
  - paramiko
  - partd
  - pip
  - pip:
    - git+https://github.com/fmidev/fmi_trollflow2_plugins.git
    - posttroll==1.12.1
    - pytroll-schedule==0.7.1
    - trollflow2==0.16.0
  - psycopg
  - pykdtree=1.4.1
  - pyorbital=1.9.2
  - pyresample=1.33.0
  - pyspectral=0.13.5
  - python=3.12
  - pyyaml
  - pyzmq
  - rasterio
  - requests>=2.32.0
  - rioxarray
  - s3fs=>2025.3.0
  - satpy=0.55.0
  - scipy
  - scp
  - shapely
  - toolz
  - trollimage=1.26.0
  - trollsift=0.5.3
  - zeromq
