channels:
  - conda-forge
dependencies:
  - aiohttp>=3.9.3
  - asciitree
  - cloudpickle
  - configobj
  - dask
  - donfig=0.8.1.post1
  - defusedxml
  - dpath
  - fasteners
  - fsspec
  - gdal
  - git
  - h5netcdf
  - h5py
  - hdf5plugin
  - locket
  - netcdf4
  - netifaces
  - numcodecs
  - numpy<2.0.0
  - paramiko
  - partd
  - pip
  - pip:
    - posttroll==1.11.0
    - pytroll-schedule==0.7.1
    - git+https://github.com/pytroll/satpy.git
    - trollflow2==0.15.3
  - pykdtree=1.3.13
  - pyorbital=1.8.3
  - pyresample=1.30.0
  - pyspectral=0.13.5
  - python=3.12
  - pyyaml
  - pyzmq
  - rasterio
  - requests>=2.32.0
  - s3fs
  # - satpy=0.50.0
  - scipy
  - scp
  - shapely
  - toolz
  - trollimage=1.25.0
  - trollsift=0.5.1
  - zeromq
