channels:
  - conda-forge
dependencies:
  - asciitree
  - configobj
  - donfig=0.8.1.post0
  - dpath
  - fasteners
  - fsspec
  - gdal
  - git
  - h5netcdf
  - h5py
  - hdf5plugin
  - netcdf4
  - netifaces
  - numcodecs
  - numpy
  - paramiko
  - pip
  - pip:
    - posttroll==1.10.0
    - trollflow2==0.15.1
  - pykdtree=1.3.10
  - pyorbital=1.8.1
  - pyresample=1.27.1
  - pyspectral=0.13.0
  - python=3.11
  - pyyaml
  - pyzmq
  - rasterio
  - s3fs
  - satpy=0.46.0
  - scipy
  - scp
  - shapely
  - toolz
  - trollimage=1.22.2
  - trollsift=0.5.1
  - zeromq
