channels:
  - conda-forge
dependencies:
  - aiohttp>=3.13.2
  - asciitree
  - botocore
  - cloudpickle
  - configobj
  - cryptography>=46.0.3
  - dask
  - dask-expr
  - dask-image
  - donfig=0.8.1.post1
  - defusedxml
  - dpath
  - fasteners
  - fsspec
  - gdal
  - git
  - h5netcdf
  - h5py
  - hdf5plugin
  - jinja2>=3.1.6
  - locket
  - netcdf4
  - netifaces
  - numcodecs
  - numpy
  - paramiko
  - partd
  - pip
  - pip:
    - git+https://github.com/fmidev/fmi_trollflow2_plugins.git@v2026-03-12
    - posttroll==1.14.0
    - pytroll-schedule==0.7.5
    - trollflow2==0.18.0
  - psycopg
  - pykdtree=1.4.3
  - pyorbital=1.12.1
  - pyresample=1.35.0
  - pyspectral=0.14.2
  - python=3.13
  - pyyaml
  - pyzmq
  - rasterio
  - requests>=2.32.5
  - rioxarray
  - s3fs>=2026.2.0
  - satpy=0.60.0
  - scipy
  - scp
  - shapely
  - toolz
  - trollimage=1.28.0
  - trollsift=1.0.0
  - zeromq
